/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FraktLeveransRouteImport } from './routes/frakt-leverans'
import { Route as GarantiRouteImport } from './routes/garanti'
import { Route as ReturRouteImport } from './routes/retur'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as ProduktHandleRouteImport } from './routes/produkt.$handle'
import { Route as ApiPublicFirecrawlCrawlRouteImport } from './routes/api/public/firecrawl-crawl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FraktLeveransRoute = FraktLeveransRouteImport.update({
  id: '/frakt-leverans',
  path: '/frakt-leverans',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiRoute = GarantiRouteImport.update({
  id: '/garanti',
  path: '/garanti',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturRoute = ReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktHandleRoute = ProduktHandleRouteImport.update({
  id: '/produkt/$handle',
  path: '/produkt/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFirecrawlCrawlRoute = ApiPublicFirecrawlCrawlRouteImport.update({
  id: '/api/public/firecrawl-crawl',
  path: '/api/public/firecrawl-crawl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/frakt-leverans': typeof FraktLeveransRoute
  '/garanti': typeof GarantiRoute
  '/retur': typeof ReturRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$handle': typeof ProduktHandleRoute
  '/api/public/firecrawl-crawl': typeof ApiPublicFirecrawlCrawlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/frakt-leverans': typeof FraktLeveransRoute
  '/garanti': typeof GarantiRoute
  '/retur': typeof ReturRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$handle': typeof ProduktHandleRoute
  '/api/public/firecrawl-crawl': typeof ApiPublicFirecrawlCrawlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/frakt-leverans': typeof FraktLeveransRoute
  '/garanti': typeof GarantiRoute
  '/retur': typeof ReturRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/produkt/$handle': typeof ProduktHandleRoute
  '/api/public/firecrawl-crawl': typeof ApiPublicFirecrawlCrawlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/frakt-leverans'
    | '/garanti'
    | '/retur'
    | '/kategori/$slug'
    | '/produkt/$handle'
    | '/api/public/firecrawl-crawl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/frakt-leverans'
    | '/garanti'
    | '/retur'
    | '/kategori/$slug'
    | '/produkt/$handle'
    | '/api/public/firecrawl-crawl'
  id:
    | '__root__'
    | '/'
    | '/frakt-leverans'
    | '/garanti'
    | '/retur'
    | '/kategori/$slug'
    | '/produkt/$handle'
    | '/api/public/firecrawl-crawl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FraktLeveransRoute: typeof FraktLeveransRoute
  GarantiRoute: typeof GarantiRoute
  ReturRoute: typeof ReturRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  ProduktHandleRoute: typeof ProduktHandleRoute
  ApiPublicFirecrawlCrawlRoute: typeof ApiPublicFirecrawlCrawlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frakt-leverans': {
      id: '/frakt-leverans'
      path: '/frakt-leverans'
      fullPath: '/frakt-leverans'
      preLoaderRoute: typeof FraktLeveransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garanti': {
      id: '/garanti'
      path: '/garanti'
      fullPath: '/garanti'
      preLoaderRoute: typeof GarantiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retur': {
      id: '/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$handle': {
      id: '/produkt/$handle'
      path: '/produkt/$handle'
      fullPath: '/produkt/$handle'
      preLoaderRoute: typeof ProduktHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firecrawl-crawl': {
      id: '/api/public/firecrawl-crawl'
      path: '/api/public/firecrawl-crawl'
      fullPath: '/api/public/firecrawl-crawl'
      preLoaderRoute: typeof ApiPublicFirecrawlCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FraktLeveransRoute: FraktLeveransRoute,
  GarantiRoute: GarantiRoute,
  ReturRoute: ReturRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  ProduktHandleRoute: ProduktHandleRoute,
  ApiPublicFirecrawlCrawlRoute: ApiPublicFirecrawlCrawlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
